# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-07 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='liitokala/uploads')),
                ('_last_reindexed', models.DateTimeField(blank=True, null=True)),
                ('_search_document', models.TextField(blank=True)),
                ('_needs_reindexing', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
