# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, upload_to='polytranspoc/uploads'),
        ),
    ]
