# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-07 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20160706_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='_last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='_last_reindexed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='_search_document',
            field=models.TextField(blank=True),
        ),
    ]
