# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20160707_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='_last_modified',
        ),
        migrations.AddField(
            model_name='content',
            name='_needs_reindexing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='content',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
